name: lineal-amp
description: |
  Demo amp to see how to approach amp development. It goes through the different
  tools CML has to help Data teams to do MLOps.

author: luis
specification_version: 1.0
prototype_version: 1.0
date: "2023-10-12"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: prepare enviroment
    script: 00-prepare-steps/prepare_steps.py
    short_summary: create project structure 
    long_summary: creates project structures, and any prepare steps
    kernel: python3
    cpu: 1
    memory: 2

  - type: run_session
    name: run a test
    script: experiments/test.py
    short_summary: test args in file 
    long_summary: checking that the task runs
    kernel: python3
    cpu: 1
    memory: 2

  - type: run_session
    name: install dependencies
    script: 01-install-dep/install_dep.py
    short_summary: install dependencies
    long_summary: install dependencies for the current project 
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_session
    name: base line run
    script: experiments/experiment_mlflow.py
    short_summary: train lineal model 
    long_summary: first baseline run
    kernel: python3
    cpu: 2
    memory: 4

  - type: create_job
    name: train model and log params
    entity_label: train_lineal
    script: experiments/experiment_mlflow.py
    arguments: true 1000
    short_summary: train lineal model job 
    long_summary: >-
      job for executing different training sessions.
      accepts arguments <intercept: boolean, cap_departure_dely: int>
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_job
    entity_label: train_lineal
    short_summary: Running train and model
  
  - type: create_job
    name: dowload run artifacts(models)
    entity_label: dowload_lineal_artifacts
    script: models/get_mlflow_run_query_based.py
    short_summary: get model from run 
    long_summary: get model from run base on some metric
    kernel: python3
    cpu: 1
    memory: 1

  - type: run_job
    entity_label: dowload_lineal_artifacts
    short_summary: dowload lineal artifacts
  
  - type: create_model
    name: create the model
    entity_label: lineal-model
    description: create model step
    short_summary: creates the model entry definitions

  - type: build_model
    entity_label: lineal-model
    comment: Build lineal model to be used for inference
    examples:
      - request:
          dep_delay: 43
        response: 
          pred_arr_delay: 38
    target_file_path: models/model.py
    target_function_name: pred_arr_delay
    kernel: python3

  - type: deploy_model
    entity_label: lineal-model 
  
  - type: start_application
    name: Lineal Predictor
    subdomain: lineal
    script: apps/app_entrypoint.py
    short_summary: An app to showcase a lineal predictor 
    long_summary: App that will do some processing using the deployed model
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION